// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chat": {
            "post": {
                "description": "向 AI 发送消息并获取回复，支持通过 messageId 继续对话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "发送对话消息",
                "parameters": [
                    {
                        "description": "对话请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回 AI 回复",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_model_ChatResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "参数验证失败",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "AI 服务不可用",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/abort": {
            "post": {
                "description": "中止指定消息的对话处理",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "中止对话",
                "parameters": [
                    {
                        "description": "中止请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.AbortRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功中止对话",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "消息不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "参数验证失败",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/messages/{id}": {
            "get": {
                "description": "根据消息ID获取消息的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "获取消息详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "消息ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回消息详情",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_service_session_MessageDetailResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "无权访问",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "消息不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/messages/{id}/abort": {
            "post": {
                "description": "中止指定消息的AI生成过程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "中止消息生成",
                "parameters": [
                    {
                        "type": "string",
                        "description": "消息ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功中止消息生成",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "无权访问",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "消息不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/sessions": {
            "get": {
                "description": "获取用户的会话列表，支持分页和过滤",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "获取会话列表",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "pageNo",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "每页大小",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "是否置顶",
                        "name": "isPinned",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "是否归档",
                        "name": "isArchived",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "模型名称",
                        "name": "modelName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回会话列表",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponsePaginationData-array_genkit-ai-service_internal_model_SessionResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "参数验证失败",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的聊天会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "创建新会话",
                "parameters": [
                    {
                        "description": "创建会话请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.CreateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功创建会话",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_model_SessionResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "参数验证失败",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/sessions/search": {
            "get": {
                "description": "根据关键词搜索会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "搜索会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "pageNo",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "每页大小",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回搜索结果",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponsePaginationData-array_genkit-ai-service_internal_model_SessionResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "参数验证失败",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/sessions/{id}": {
            "get": {
                "description": "根据会话ID获取会话的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "获取会话详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回会话详情",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_model_SessionResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "无权访问",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "会话不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "软删除指定的会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "删除会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功删除会话",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "无权访问",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "会话不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "更新会话的标题、配置等信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "更新会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新会话请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.UpdateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功更新会话",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_model_SessionResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "无权访问",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "会话不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "参数验证失败",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/sessions/{id}/archive": {
            "post": {
                "description": "归档或取消归档指定的会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "归档会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "是否归档",
                        "name": "archived",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功更新归档状态",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "无权访问",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "会话不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/sessions/{id}/messages": {
            "get": {
                "description": "获取指定会话的消息历史，支持分页",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "获取消息历史",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "pageNo",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 50,
                        "description": "每页大小",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回消息历史",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponsePaginationData-array_genkit-ai-service_internal_service_session_MessageDetailResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "无权访问",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "会话不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "参数验证失败",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "在指定会话中发送消息并获取AI回复",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "发送消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "发送消息请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功发送消息",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_service_session_MessageResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "无权访问",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "会话不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "参数验证失败",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/chat/sessions/{id}/pin": {
            "post": {
                "description": "置顶或取消置顶指定的会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "置顶会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "是否置顶",
                        "name": "pinned",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功更新置顶状态",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-any"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "无权访问",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "会话不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "检查服务及其依赖项的健康状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "服务健康",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.HealthStatusResponse"
                        }
                    },
                    "500": {
                        "description": "健康检查失败",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "服务不健康",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/providers": {
            "get": {
                "description": "获取系统中所有可用的模型提供商列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "获取所有提供商列表",
                "responses": {
                    "200": {
                        "description": "成功返回提供商列表",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-array_genkit-ai-service_internal_model_Provider"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/providers/{providerId}": {
            "get": {
                "description": "根据提供商ID获取详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "获取提供商详情",
                "parameters": [
                    {
                        "type": "string",
                        "example": "gemini",
                        "description": "提供商ID",
                        "name": "providerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回提供商详情",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_model_Provider"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "提供商不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/providers/{providerId}/models": {
            "get": {
                "description": "获取指定提供商的所有可用模型列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "获取提供商的模型列表",
                "parameters": [
                    {
                        "type": "string",
                        "example": "gemini",
                        "description": "提供商ID",
                        "name": "providerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回模型列表",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-array_genkit-ai-service_internal_model_Model"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "提供商不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/providers/{providerId}/models/{modelId}": {
            "get": {
                "description": "获取指定提供商的指定模型的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "获取模型详情",
                "parameters": [
                    {
                        "type": "string",
                        "example": "gemini",
                        "description": "提供商ID",
                        "name": "providerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "gemini-1.5-flash",
                        "description": "模型ID",
                        "name": "modelId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回模型详情",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_model_Model"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "提供商或模型不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/providers/{providerId}/models/{modelId}/parameter-rules": {
            "get": {
                "description": "获取指定模型的所有参数配置规则",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "获取模型参数规则",
                "parameters": [
                    {
                        "type": "string",
                        "example": "gemini",
                        "description": "提供商ID",
                        "name": "providerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "gemini-1.5-flash",
                        "description": "模型ID",
                        "name": "modelId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回参数规则列表",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ResponseData-array_genkit-ai-service_internal_model_ParameterRule"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "提供商或模型不存在",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "genkit-ai-service_internal_model.AbortRequest": {
            "type": "object",
            "required": [
                "messageId"
            ],
            "properties": {
                "messageId": {
                    "description": "消息ID（必填）",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "genkit-ai-service_internal_model.ChatOptions": {
            "type": "object",
            "properties": {
                "maxTokens": {
                    "description": "最大token数",
                    "type": "integer",
                    "example": 2048
                },
                "temperature": {
                    "description": "温度值，控制输出的随机性（0-2）",
                    "type": "number",
                    "maximum": 2,
                    "minimum": 0,
                    "example": 0.7
                },
                "topK": {
                    "description": "Top-K采样参数",
                    "type": "integer",
                    "example": 40
                },
                "topP": {
                    "description": "Top-P采样参数（0-1）",
                    "type": "number",
                    "maximum": 1,
                    "minimum": 0,
                    "example": 0.9
                }
            }
        },
        "genkit-ai-service_internal_model.ChatRequest": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "description": "用户消息内容",
                    "type": "string",
                    "example": "你好，请介绍一下你自己"
                },
                "messageId": {
                    "description": "消息ID（可选，用于继续对话）",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "options": {
                    "description": "AI高级参数（可选）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ChatOptions"
                        }
                    ]
                }
            }
        },
        "genkit-ai-service_internal_model.ChatResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "AI生成的消息内容",
                    "type": "string",
                    "example": "你好！我是一个 AI 助手..."
                },
                "model": {
                    "description": "使用的模型名称",
                    "type": "string",
                    "example": "gemini-1.5-flash"
                },
                "sessionId": {
                    "description": "会话ID",
                    "type": "string",
                    "example": "session-123456"
                },
                "usage": {
                    "description": "Token使用情况",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.Usage"
                        }
                    ]
                }
            }
        },
        "genkit-ai-service_internal_model.CreateSessionRequest": {
            "type": "object",
            "required": [
                "modelName",
                "title"
            ],
            "properties": {
                "meta": {
                    "description": "元数据（可选）",
                    "type": "object",
                    "additionalProperties": true
                },
                "modelName": {
                    "description": "模型名称",
                    "type": "string",
                    "maxLength": 128,
                    "example": "gpt-4"
                },
                "systemPrompt": {
                    "description": "系统提示词（可选）",
                    "type": "string",
                    "example": "你是一个有帮助的AI助手"
                },
                "temperature": {
                    "description": "温度参数（可选，0-2）",
                    "type": "number",
                    "maximum": 2,
                    "minimum": 0,
                    "example": 0.7
                },
                "title": {
                    "description": "会话标题",
                    "type": "string",
                    "maxLength": 255,
                    "example": "我的第一个会话"
                },
                "topP": {
                    "description": "TopP参数（可选，0-1）",
                    "type": "number",
                    "maximum": 1,
                    "minimum": 0,
                    "example": 0.9
                }
            }
        },
        "genkit-ai-service_internal_model.CredentialFormSchema": {
            "type": "object",
            "properties": {
                "default": {
                    "description": "默认值",
                    "type": "string"
                },
                "label": {
                    "description": "标签（多语言）",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "options": {
                    "description": "选项列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/genkit-ai-service_internal_model.FormOption"
                    }
                },
                "placeholder": {
                    "description": "占位符（多语言）",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "required": {
                    "description": "是否必填",
                    "type": "boolean"
                },
                "type": {
                    "description": "类型",
                    "type": "string"
                },
                "variable": {
                    "description": "变量名",
                    "type": "string"
                }
            }
        },
        "genkit-ai-service_internal_model.CredentialSchema": {
            "type": "object",
            "properties": {
                "credential_form_schemas": {
                    "description": "凭证表单配置列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/genkit-ai-service_internal_model.CredentialFormSchema"
                    }
                }
            }
        },
        "genkit-ai-service_internal_model.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "请求参数错误"
                }
            }
        },
        "genkit-ai-service_internal_model.FormOption": {
            "type": "object",
            "properties": {
                "label": {
                    "description": "选项标签（多语言）",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "value": {
                    "description": "选项值",
                    "type": "string"
                }
            }
        },
        "genkit-ai-service_internal_model.MessagePreview": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "消息内容",
                    "type": "string",
                    "example": "你好"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "id": {
                    "description": "消息ID",
                    "type": "string",
                    "example": "msg-123456"
                },
                "role": {
                    "description": "角色",
                    "type": "string",
                    "example": "user"
                }
            }
        },
        "genkit-ai-service_internal_model.Model": {
            "type": "object",
            "properties": {
                "deprecated": {
                    "description": "是否已弃用",
                    "type": "boolean",
                    "example": false
                },
                "features": {
                    "description": "特性列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "tool-call",
                        "multi-tool-call",
                        "stream-tool-call"
                    ]
                },
                "label": {
                    "description": "多语言标签",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "en_US": "Gemini 1.5 Flash",
                        "zh_Hans": "Gemini 1.5 Flash"
                    }
                },
                "model": {
                    "description": "模型标识",
                    "type": "string",
                    "example": "gemini-1.5-flash"
                },
                "model_properties": {
                    "description": "模型属性",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ModelProperties"
                        }
                    ]
                },
                "model_type": {
                    "description": "模型类型（llm、tts、text_embedding等）",
                    "type": "string",
                    "example": "llm"
                },
                "parameter_rules": {
                    "description": "参数规则",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/genkit-ai-service_internal_model.ParameterRule"
                    }
                },
                "pricing": {
                    "description": "定价信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.Pricing"
                        }
                    ]
                }
            }
        },
        "genkit-ai-service_internal_model.ModelProperties": {
            "type": "object",
            "properties": {
                "context_size": {
                    "description": "上下文大小",
                    "type": "integer"
                },
                "mode": {
                    "description": "模式（chat、completion等）",
                    "type": "string"
                }
            }
        },
        "genkit-ai-service_internal_model.ModelTypeInfo": {
            "type": "object",
            "properties": {
                "position": {
                    "description": "位置文件路径",
                    "type": "string"
                },
                "predefined": {
                    "description": "预定义模型列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "genkit-ai-service_internal_model.PaginationData-array_genkit-ai-service_internal_model_SessionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/genkit-ai-service_internal_model.SessionResponse"
                    }
                },
                "pageNo": {
                    "description": "当前页码",
                    "type": "integer",
                    "example": 1
                },
                "pageSize": {
                    "description": "每页大小",
                    "type": "integer",
                    "example": 10
                },
                "totalCount": {
                    "description": "总记录数",
                    "type": "integer",
                    "example": 100
                },
                "totalPage": {
                    "description": "总页数",
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "genkit-ai-service_internal_model.PaginationData-array_genkit-ai-service_internal_service_session_MessageDetailResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/genkit-ai-service_internal_service_session.MessageDetailResponse"
                    }
                },
                "pageNo": {
                    "description": "当前页码",
                    "type": "integer",
                    "example": 1
                },
                "pageSize": {
                    "description": "每页大小",
                    "type": "integer",
                    "example": 10
                },
                "totalCount": {
                    "description": "总记录数",
                    "type": "integer",
                    "example": 100
                },
                "totalPage": {
                    "description": "总页数",
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "genkit-ai-service_internal_model.ParameterRule": {
            "type": "object",
            "properties": {
                "default": {
                    "description": "默认值"
                },
                "help": {
                    "description": "帮助信息（多语言）",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "label": {
                    "description": "标签（多语言）",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "max": {
                    "description": "最大值"
                },
                "min": {
                    "description": "最小值"
                },
                "name": {
                    "description": "参数名称",
                    "type": "string",
                    "example": "temperature"
                },
                "options": {
                    "description": "选项列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "required": {
                    "description": "是否必填",
                    "type": "boolean",
                    "example": false
                },
                "type": {
                    "description": "类型",
                    "type": "string",
                    "example": "float"
                },
                "use_template": {
                    "description": "使用的模板",
                    "type": "string",
                    "example": "temperature"
                }
            }
        },
        "genkit-ai-service_internal_model.Pricing": {
            "type": "object",
            "properties": {
                "currency": {
                    "description": "货币",
                    "type": "string"
                },
                "input": {
                    "description": "输入价格",
                    "type": "string"
                },
                "output": {
                    "description": "输出价格",
                    "type": "string"
                },
                "unit": {
                    "description": "单位",
                    "type": "string"
                }
            }
        },
        "genkit-ai-service_internal_model.Provider": {
            "type": "object",
            "properties": {
                "background": {
                    "description": "背景色",
                    "type": "string",
                    "example": "#4285F4"
                },
                "configurate_methods": {
                    "description": "配置方法列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "predefined-model",
                        "customizable-model"
                    ]
                },
                "help": {
                    "description": "帮助信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ProviderHelp"
                        }
                    ]
                },
                "icon_large": {
                    "description": "大图标（多语言）",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "icon_small": {
                    "description": "小图标（多语言）",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "提供商ID（从文件夹名称获取）",
                    "type": "string",
                    "example": "gemini"
                },
                "label": {
                    "description": "多语言标签",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "en_US": "Google Gemini",
                        "zh_Hans": "谷歌 Gemini"
                    }
                },
                "model_credential_schema": {
                    "description": "模型凭证配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.CredentialSchema"
                        }
                    ]
                },
                "models": {
                    "description": "模型类型配置",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/genkit-ai-service_internal_model.ModelTypeInfo"
                    }
                },
                "provider": {
                    "description": "提供商标识",
                    "type": "string",
                    "example": "gemini"
                },
                "provider_credential_schema": {
                    "description": "提供商凭证配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.CredentialSchema"
                        }
                    ]
                },
                "supported_model_types": {
                    "description": "支持的模型类型列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "llm",
                        "text-embedding"
                    ]
                }
            }
        },
        "genkit-ai-service_internal_model.ProviderHelp": {
            "type": "object",
            "properties": {
                "title": {
                    "description": "帮助标题（多语言）",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "url": {
                    "description": "帮助链接（多语言）",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "genkit-ai-service_internal_model.ResponseData-any": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据"
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "genkit-ai-service_internal_model.ResponseData-array_genkit-ai-service_internal_model_Model": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/genkit-ai-service_internal_model.Model"
                    }
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "genkit-ai-service_internal_model.ResponseData-array_genkit-ai-service_internal_model_ParameterRule": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/genkit-ai-service_internal_model.ParameterRule"
                    }
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "genkit-ai-service_internal_model.ResponseData-array_genkit-ai-service_internal_model_Provider": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/genkit-ai-service_internal_model.Provider"
                    }
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_model_ChatResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ChatResponse"
                        }
                    ]
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_model_Model": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.Model"
                        }
                    ]
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_model_Provider": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.Provider"
                        }
                    ]
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_model_SessionResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.SessionResponse"
                        }
                    ]
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_service_session_MessageDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_service_session.MessageDetailResponse"
                        }
                    ]
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "genkit-ai-service_internal_model.ResponseData-genkit-ai-service_internal_service_session_MessageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_service_session.MessageResponse"
                        }
                    ]
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "genkit-ai-service_internal_model.ResponsePaginationData-array_genkit-ai-service_internal_model_SessionResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "分页数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.PaginationData-array_genkit-ai-service_internal_model_SessionResponse"
                        }
                    ]
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "genkit-ai-service_internal_model.ResponsePaginationData-array_genkit-ai-service_internal_service_session_MessageDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "分页数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.PaginationData-array_genkit-ai-service_internal_service_session_MessageDetailResponse"
                        }
                    ]
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "genkit-ai-service_internal_model.SendMessageRequest": {
            "type": "object",
            "required": [
                "message",
                "sessionId"
            ],
            "properties": {
                "message": {
                    "description": "消息内容",
                    "type": "string",
                    "example": "你好，请介绍一下你自己"
                },
                "options": {
                    "description": "AI高级参数（可选）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.ChatOptions"
                        }
                    ]
                },
                "sessionId": {
                    "description": "会话ID",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "genkit-ai-service_internal_model.SessionResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "创建时间",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "id": {
                    "description": "会话ID",
                    "type": "string",
                    "example": "session-123456"
                },
                "isArchived": {
                    "description": "是否归档",
                    "type": "boolean",
                    "example": false
                },
                "isPinned": {
                    "description": "是否置顶",
                    "type": "boolean",
                    "example": false
                },
                "lastMessage": {
                    "description": "最后一条消息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/genkit-ai-service_internal_model.MessagePreview"
                        }
                    ]
                },
                "messageCount": {
                    "description": "消息数量",
                    "type": "integer",
                    "example": 10
                },
                "meta": {
                    "description": "元数据",
                    "type": "object",
                    "additionalProperties": true
                },
                "modelName": {
                    "description": "模型名称",
                    "type": "string",
                    "example": "gpt-4"
                },
                "systemPrompt": {
                    "description": "系统提示词",
                    "type": "string",
                    "example": "你是一个有帮助的AI助手"
                },
                "temperature": {
                    "description": "温度参数",
                    "type": "number",
                    "example": 0.7
                },
                "title": {
                    "description": "会话标题",
                    "type": "string",
                    "example": "我的第一个会话"
                },
                "topP": {
                    "description": "TopP参数",
                    "type": "number",
                    "example": 0.9
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "userId": {
                    "description": "用户ID",
                    "type": "string",
                    "example": "user-123456"
                }
            }
        },
        "genkit-ai-service_internal_model.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应代码",
                    "type": "integer",
                    "example": 200
                },
                "message": {
                    "description": "响应信息",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "genkit-ai-service_internal_model.UpdateSessionRequest": {
            "type": "object",
            "properties": {
                "modelName": {
                    "description": "模型名称（可选）",
                    "type": "string",
                    "maxLength": 128,
                    "example": "gpt-4-turbo"
                },
                "systemPrompt": {
                    "description": "系统提示词（可选）",
                    "type": "string",
                    "example": "你是一个专业的编程助手"
                },
                "temperature": {
                    "description": "温度参数（可选，0-2）",
                    "type": "number",
                    "maximum": 2,
                    "minimum": 0,
                    "example": 0.8
                },
                "title": {
                    "description": "会话标题（可选）",
                    "type": "string",
                    "maxLength": 255,
                    "example": "更新后的标题"
                },
                "topP": {
                    "description": "TopP参数（可选，0-1）",
                    "type": "number",
                    "maximum": 1,
                    "minimum": 0,
                    "example": 0.95
                }
            }
        },
        "genkit-ai-service_internal_model.Usage": {
            "type": "object",
            "properties": {
                "completionTokens": {
                    "description": "生成内容token数",
                    "type": "integer",
                    "example": 50
                },
                "promptTokens": {
                    "description": "提示词token数",
                    "type": "integer",
                    "example": 10
                },
                "totalTokens": {
                    "description": "总token数",
                    "type": "integer",
                    "example": 60
                }
            }
        },
        "genkit-ai-service_internal_service_health.HealthStatus": {
            "type": "object",
            "properties": {
                "dependencies": {
                    "description": "依赖服务状态",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "database": "connected",
                        "genkit": "connected"
                    }
                },
                "status": {
                    "description": "整体状态：healthy, unhealthy",
                    "type": "string",
                    "example": "healthy"
                },
                "uptime": {
                    "description": "运行时间",
                    "type": "string",
                    "example": "2h30m15s"
                },
                "version": {
                    "description": "服务版本",
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "genkit-ai-service_internal_service_session.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                }
            }
        },
        "genkit-ai-service_internal_service_session.MessageDetailResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": true
                },
                "role": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                },
                "sessionId": {
                    "type": "string"
                },
                "tokens": {
                    "type": "integer"
                },
                "toolCalls": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "genkit-ai-service_internal_service_session.MessageResponse": {
            "type": "object",
            "properties": {
                "aiMessage": {
                    "$ref": "#/definitions/genkit-ai-service_internal_service_session.Message"
                },
                "messageId": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "sessionId": {
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/genkit-ai-service_internal_model.Usage"
                },
                "userMessage": {
                    "$ref": "#/definitions/genkit-ai-service_internal_service_session.Message"
                }
            }
        },
        "internal_api_handler.HealthStatusResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/genkit-ai-service_internal_service_health.HealthStatus"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        }
    },
    "tags": [
        {
            "description": "模型提供商管理接口",
            "name": "providers"
        },
        {
            "description": "AI 对话接口",
            "name": "chat"
        },
        {
            "description": "健康检查接口",
            "name": "health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Genkit AI Service API",
	Description:      "AI 模型提供商管理服务 API 文档\n提供模型提供商、模型信息和参数规则的查询接口",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
